<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_MANAGEMENT</name>
   <tag></tag>
   <elementGuidId>ffc18204-5942-4ce6-b919-92e0fe187ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div/div/div/h5[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>83368bc1-699c-4318-96b4-74e19a1d8b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 css-zq6grw</value>
      <webElementGuid>67c98a92-fd49-45c9-87e6-acaa46e28172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MANAGEMENT</value>
      <webElementGuid>80e30ebf-6771-4e0e-8fe9-6e8b21f26c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[3]/div[1]/div[@class=&quot;white-card&quot;]/div[1]/div[1]/h5[@class=&quot;MuiTypography-root MuiTypography-h5 css-zq6grw&quot;]</value>
      <webElementGuid>c3d5d539-3af6-471b-9b1c-1bec6610f33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/div/div/h5[2]</value>
      <webElementGuid>045cca59-0d83-41b5-bed0-18022a0204bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDC BOOTCAMP'])[1]/following::h5[1]</value>
      <webElementGuid>f62ddbff-af05-4e39-a2ec-4a679ecee113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::h5[1]</value>
      <webElementGuid>73e67441-2268-40fa-b715-be7b0a2a3aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with Microsoft'])[1]/preceding::h5[2]</value>
      <webElementGuid>462529da-c8e0-454c-b7c2-ee99901517d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MANAGEMENT']/parent::*</value>
      <webElementGuid>f5b9b133-3a7c-4bbb-895f-987323d054c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5[2]</value>
      <webElementGuid>8b9cd3bd-f47e-4f5b-9dac-28886540362b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'MANAGEMENT' or . = 'MANAGEMENT')]</value>
      <webElementGuid>c5742dbd-dc46-4c53-881f-dff9bf1b1ee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
